library:
  source-dirs: src
tests:
  lightmath-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lightmath
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
- containers
- base >= 4.7 && < 5
- mtl
- serverless-haskell
- aeson
- lens
name: lightmath
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/lightmath
license: BSD3
default-extensions: LambdaCase, TupleSections
executables:
  lightmath-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lightmath
description: Please see the README on GitHub at <https://github.com/githubuser/lightmath#readme>
